### ISSUE TITLE
Add launcher script to allow selection of tools to launch

### ISSUE THREAD

**Issue by sethforprivacy** [sethforprivacy/self-hosted-services#2]
As this project grows I would love to have a simple launcher script for selecting which apps to launch, accessing logs, and managing the compose stack.

**Comment by mutefall** [comment]
@sethforprivacy may want to consider `makefile` strategy thus an operator can exec:

- `make deploy all`
- `make deploy traefik nitter teddit` 

make is a very well-known build mechanism and worth looking into.  many of us in the container realm are using it as a simple build abstraction.

**Comment by sethforprivacy** [comment]
That would be ideal, will have to look into that! If you're familiar I'd gladly accept a PR around that, and would tip in Monero for any work around that.

**Comment by kubo6472** [comment]
@sethforprivacy Use multiple compose files. Each containing one service. Then have some website, like e.g. https://startmc.sh/ to select which programs one wants to run, and it will generate the startup command for those docker-compose files. More details here: https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

**Comment by sethforprivacy** [comment]
Will be solved through migrating to tipi: https://github.com/meienberger/runtipi

**Comment by kubo6472** [comment]
Sad to see this go, but I hope it will be for the better. I deploy this statically, so I will keep on using this as long as it keeps to exist.

**Comment by sethforprivacy** [comment]
If nothing else I'll just archive and leave it up, but anyone is always welcome to fork and maintain it -- Tipi just much better fits the end-user I have in mind, and easily supports all the same apps.
