### ISSUE TITLE
Cannot Pull Send Image

### ISSUE THREAD

**Issue by NeonMinnen** [sethforprivacy/self-hosted-services#25]
Hiya.

I'm getting this error while trying to pull the send image.

`error pulling image configuration: download failed after attempts=1: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>403 Forbidden</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Forbidden</h1>\n<h2>Your client does not have permission to get URL <code>/gitlab/docker/registry/v2/blobs/sha256/4e/4ede285a2b79c16f2e1914ac09351fe5db66af7819987a145014dbc2b581f71e/data</code> from this server.</h2>\n<h2></h2>\n</body></html>\n"`

Any fix for this?

**Comment by NeonMinnen** [comment]
@sethforprivacy Hmm. Very strange.. I just tried that, and I'm still getting the same error. This is on a Hetzner VPS, so not sure why I would be blocked.

**Comment by sethforprivacy** [comment]
I'm also doing it from multiple VPS, all without issues -- have you accidentally changed some Docker settings around container registries or something? AFAIK this is not a global issue, and this is still the listed place for Send images per the docs:

https://github.com/timvisee/send/blob/master/docs/docker.md

**Comment by NeonMinnen** [comment]
Very strange. I checked as well, and that is the listed placed for the image. I haven't done anything to the docker settings. It's basically a fresh VPS install with docker, and docker-compose.

**Comment by sethforprivacy** [comment]
Yeah, sorry :( Maybe try reaching out to the actual owner of Send? I don't have any control over that and as it's working for me there isn't anything else I can do to help, sadly!
