### ISSUE TITLE
Error xmrblocks:latest

### ISSUE THREAD

**Issue by vbrekher** [sethforprivacy/self-hosted-services#36]
Failed to find sethsimmons/xmrblocks:latest

**Comment by sethforprivacy** [comment]
Ah, yes, I took down my image.

Use this one now, I'll update the compose file:

`vdo1138/xmrblocks:latest`

**Comment by sethforprivacy** [comment]
Fixed in https://github.com/sethforprivacy/self-hosted-services/commit/de1a71350d4f82aa05121f6f59d4c46807964238
